/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const IconCarbonApps: typeof import('~icons/carbon/apps.jsx')['default']
  const IconTablerCheck: typeof import('~icons/tabler/check.jsx')['default']
  const IconTablerPlus: typeof import('~icons/tabler/plus.jsx')['default']
  const IconTablerTrash: typeof import('~icons/tabler/trash.jsx')['default']
  const IconTablerWand: typeof import('~icons/tabler/wand.jsx')['default']
}
